[ECB-95] Added api.depends to _compute_weight
DynAppsNV/eurocable pull request #14
Opened 2024-10-25 09:50 UTC by dynapps-nielsgebruers

2024-10-25 11:53 UTC, siemenv requested changes

2024-10-25 11:53 UTC, siemenv commented on addons/eurocable_mrp/models/sale_order_line.py
> +        "product_id", "product_id.weight", "product_id.bom_ids", "order_id.mrp_production_ids"
"product_id" is overbodig
order_id.production_ids.product_id niet nodig?

2024-10-25 14:11 UTC, siemenv approved these changes

2024-10-29 15:14 UTC, dynapps approved these changes

2024-10-29 15:30 UTC, merged